version: '3.8'

services:
  web:
    build:
      context: .
      
    ports:
      - "5010:5010"

    volumes:
      - .:/app

    environment:
       FLASK_ENV: development
       FLASK_DEBUG: 1 

