name: CI/CD Pipeline for Docker App

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:

  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false # Để các job khác tiếp tục chạy nếu một phiên bản thất bại
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11'] # Liệt kê các phiên bản Python muốn test
    
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Cài đặt thư viện từ requirements.txt
          pip install pytest # Cài đặt pytest để chạy tests

      - name: Run tests
        run: pytest


  build_and_push:

    needs: test

    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }}   

      - name: Build and tag Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ci_docker_project:v1 .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ci_docker_project:v1


