# Tên của workflow, hiển thị trên tab Actions của GitHub
name: CI/CD Pipeline for Docker App

# Các sự kiện kích hoạt workflow
on:
  push:
    branches:
      - main # Chạy khi có push lên nhánh main
  pull_request:
    branches:
      - main # Chạy khi có pull request vào nhánh main

jobs:
  # Job 1: Chạy kiểm thử ứng dụng
  test:
    # Chạy trên máy ảo Ubuntu mới nhất do GitHub cung cấp
    runs-on: ubuntu-latest
    steps:
      # Bước 1: Checkout mã nguồn từ kho lưu trữ
      - name: Checkout repository
        uses: actions/checkout@v4 # Sử dụng action chính thức để checkout code

      # Bước 2: Cài đặt môi trường Python
      - name: Set up Python
        uses: actions/setup-python@v5 # Sử dụng action chính thức để cài Python
        with:
          python-version: '3.9' # Chỉ định phiên bản Python như trong Dockerfile

      # Bước 3: Cài đặt các thư viện phụ thuộc và pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Cài đặt thư viện từ requirements.txt
          pip install pytest # Cài đặt pytest để chạy tests

      # Bước 4: Chạy các bài kiểm thử bằng pytest
      # Lệnh `pytest` sẽ tự động tìm các tệp và hàm test trong thư mục tests/
      - name: Run tests
        run: pytest

  # Job 2: Xây dựng và đẩy Docker image lên Docker Hub
  build_and_push:
    # Job này chỉ chạy nếu job 'test' hoàn thành thành công
    needs: test
    # Chạy trên máy ảo Ubuntu mới nhất
    runs-on: ubuntu-latest
    # Chỉ thực hiện các bước đẩy image khi sự kiện là push vào nhánh main
    # Điều này tránh việc đẩy image từ các pull request chưa được merge
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Đăng nhập vào Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3 # Sử dụng action chính thức để đăng nhập Docker
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Lấy username từ GitHub Secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}    # Lấy access token từ GitHub Secrets

      # Bước 3: Xây dựng Docker image và gắn thẻ (tag)
      # Thay thế 'your-dockerhub-username' và 'your-repo-name' bằng thông tin của bạn
      - name: Build and tag Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ci_docker_project:v1v1 .
        # Ví dụ: docker build -t mydockeruser/myflaskapp:latest .

      # Bước 4: Đẩy (push) Docker image lên Docker Hub
      # Thay thế 'your-dockerhub-username' và 'your-repo-name' bằng thông tin của bạn
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ci_docker_project:latest
        # Ví dụ: docker push mydockeruser/myflaskapp:latest

